// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxxSEpbCv4Unw5rTvvHFZQ10rYnm669Dw',
    appId: '1:44415798713:web:297661183d16d44d4c3a68',
    messagingSenderId: '44415798713',
    projectId: 'dap-riverpod-tp5',
    authDomain: 'dap-riverpod-tp5.firebaseapp.com',
    storageBucket: 'dap-riverpod-tp5.firebasestorage.app',
    measurementId: 'G-RWZS9TCDC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfJQsnXdqx3rfd53F4hhs3mwDBgqIanWM',
    appId: '1:44415798713:android:3222bdff2129ad794c3a68',
    messagingSenderId: '44415798713',
    projectId: 'dap-riverpod-tp5',
    storageBucket: 'dap-riverpod-tp5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX-X7E-h8RkXwVbLL1I_2joQYB5TRTImE',
    appId: '1:44415798713:ios:e062339ac75e3f894c3a68',
    messagingSenderId: '44415798713',
    projectId: 'dap-riverpod-tp5',
    storageBucket: 'dap-riverpod-tp5.firebasestorage.app',
    iosBundleId: 'com.example.dapGesterDatosLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX-X7E-h8RkXwVbLL1I_2joQYB5TRTImE',
    appId: '1:44415798713:ios:e062339ac75e3f894c3a68',
    messagingSenderId: '44415798713',
    projectId: 'dap-riverpod-tp5',
    storageBucket: 'dap-riverpod-tp5.firebasestorage.app',
    iosBundleId: 'com.example.dapGesterDatosLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxxSEpbCv4Unw5rTvvHFZQ10rYnm669Dw',
    appId: '1:44415798713:web:262f0033bc6f76e04c3a68',
    messagingSenderId: '44415798713',
    projectId: 'dap-riverpod-tp5',
    authDomain: 'dap-riverpod-tp5.firebaseapp.com',
    storageBucket: 'dap-riverpod-tp5.firebasestorage.app',
    measurementId: 'G-1H79ZYKFJB',
  );
}
